import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const toolsDir = path.dirname( fileURLToPath( import.meta.url ) );
const gameLabRoot = path.resolve( toolsDir, '..' );
const outputRelative =
	'games/popup-breaker/assets/popup-siege-runtime-0.7.0.js';
const inputs = Object.freeze( [
	'sdk/openstation-game-kit-0.1.0.js',
	'sdk/openstation-game-kit-0.1.1.js',
	'sdk/openstation-audio-kit-0.1.0.js',
	...[
		'0.2.0',
		'0.2.1',
		'0.3.0',
		'0.4.0',
		'0.4.1',
		'0.4.2',
		'0.4.3',
		'0.4.4',
		'0.4.5',
		'0.4.6',
		'0.4.7',
		'0.4.8',
		'0.5.0',
		'0.5.1',
		'0.6.0',
		'0.6.1',
		'0.7.0',
	].map(
		( version ) =>
			`games/popup-breaker/assets/popup-breaker-${ version }.js`
	),
	'games/popup-breaker/assets/popup-siege-audio-0.7.0.js',
] );

function sha256( value ) {
	return crypto.createHash( 'sha256' ).update( value ).digest( 'hex' );
}

const sections = [];
const manifest = [];
for ( const relative of inputs ) {
	const absolute = path.join( gameLabRoot, relative );
	if ( ! fs.existsSync( absolute ) ) {
		throw new Error( `Missing Popup Siege runtime input: ${ relative }` );
	}
	const source = fs.readFileSync( absolute, 'utf8' ).replace( /\s+$/, '' );
	manifest.push( Object.freeze( { file: relative, sha256: sha256( source ) } ) );
	sections.push( `/* runtime input: ${ relative } */\n${ source }\n` );
}

const banner = [
	'/*! Popup Siege 0.7.0 deterministic browser runtime.',
	' * Generated by tools/build-popup-siege-runtime.mjs.',
	' * Edit the versioned inputs, then rebuild this file.',
	` * input-manifest-sha256: ${ sha256( JSON.stringify( manifest ) ) }`,
	' */',
	'',
].join( '\n' );
const output = `${ banner }${ sections.join( '\n' ) }`;
const outputAbsolute = path.join( gameLabRoot, outputRelative );
fs.writeFileSync( outputAbsolute, output, 'utf8' );

process.stdout.write(
	`Built ${ outputRelative } from ${ inputs.length } pinned inputs (${ sha256(
		output
	).slice( 0, 12 ) }).\n`
);
