import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { describe, expect, test } from 'vitest';
import { MIO_DEFAULTS } from '../../src/mio/config';
import { mioPortraitDataUri, mioPortraitSvg } from '../../src/mio/portrait';
import { mulberry32, randomMioLook } from '../../src/mio/randomize';
import type { MioConfig, MioShapePreset } from '../../src/mio/types';

const FIXTURE = resolve( __dirname, '../fixtures/mio-portraits.json' );

const PRESETS: MioShapePreset[] = [
	'circle',
	'blob',
	'ghost',
	'potato',
	'star',
	'flower',
	'heart',
	'diamond',
	'drop',
	'cloud',
];

interface Case {
	label: string;
	size: number;
	config: Partial< MioConfig >;
}

const CASES: Case[] = [
	...PRESETS.map( ( shapePreset ) => ( {
		label: `preset-${ shapePreset }`,
		size: 96,
		config: { physics: { shapePreset } } as Partial< MioConfig >,
	} ) ),
	{
		label: 'shape-amount-zero',
		size: 96,
		config: { physics: { shapePreset: 'star', shapeAmount: 0 } },
	},
	{
		label: 'shape-rotated',
		size: 96,
		config: { physics: { shapePreset: 'heart', shapeAngle: 90 } },
	},
	{
		label: 'hue-loop-off',
		size: 64,
		config: { appearance: { hueLoop: false, hueStart: 40, hueSpan: 180 } },
	},
	{
		label: 'no-glow',
		size: 48,
		config: { appearance: { glow: 0, outlineWidth: 1 } },
	},
	{
		label: 'wide-eyes-translucent-body',
		size: 128,
		config: { appearance: { eyeScale: 0.55, bodyAlpha: 0.4 } },
	},
	{
		label: 'seeded-4242',
		size: 96,
		config: seededConfig( 4242 ),
	},
];

function seededConfig( seed: number ): Partial< MioConfig > {
	const look = randomMioLook( mulberry32( seed ) );
	return { appearance: look.appearance, physics: look.physics };
}

function render( c: Case ): string {
	return mioPortraitSvg( c.config, c.size, c.label );
}

describe( 'mio portraits', () => {
	test( 'match the committed fixture', () => {
		const actual = Object.fromEntries(
			CASES.map( ( c ) => [ c.label, render( c ) ] ),
		);

		if ( process.env.UPDATE_MIO_PORTRAITS ) {
			mkdirSync( dirname( FIXTURE ), { recursive: true } );
			writeFileSync(
				FIXTURE,
				JSON.stringify(
					{
						note: 'Generated by tests/vitest/mio-portrait.test.ts. The PHP twin in includes/mio-portrait.php is pinned to the same file; regenerate deliberately, never to make a test pass.',
						cases: CASES.map( ( c ) => ( {
							label: c.label,
							size: c.size,
							config: c.config,
							svg: actual[ c.label ],
						} ) ),
					},
					null,
					'\t',
				) + '\n',
			);
		}

		expect(
			existsSync( FIXTURE ),
			'tests/fixtures/mio-portraits.json is missing. Regenerate it with UPDATE_MIO_PORTRAITS=1.',
		).toBe( true );

		const fixture = JSON.parse( readFileSync( FIXTURE, 'utf8' ) ) as {
			cases: { label: string; svg: string }[];
		};
		for ( const c of fixture.cases ) {
			expect( actual[ c.label ], `portrait "${ c.label }" drifted` ).toBe(
				c.svg,
			);
		}
		expect( fixture.cases.map( ( c ) => c.label ) ).toEqual(
			CASES.map( ( c ) => c.label ),
		);
	} );

	test( 'carry no text and no caller-supplied string', () => {

		const allowed = new Set( [
			'svg',
			'defs',
			'linearGradient',
			'stop',
			'path',
			'use',
			'rect',

			'clipPath',
		] );
		for ( const c of CASES ) {
			const svg = render( c );
			const tags = [ ...svg.matchAll( /<\/?([A-Za-z][\w:-]*)/g ) ].map(
				( m ) => m[ 1 ],
			);
			for ( const tag of tags ) {
				expect( allowed.has( tag ), `unexpected <${ tag }>` ).toBe( true );
			}

			expect( svg.replace( /<[^>]*>/g, '' ) ).toBe( '' );
			expect( svg ).not.toContain( '<script' );
			expect( svg ).not.toContain( 'xlink' );
		}
	} );

	test( 'scope their ids so several can share one document', () => {

		const a = mioPortraitSvg( { physics: { shapePreset: 'star' } }, 96, 'a' );
		const b = mioPortraitSvg( { physics: { shapePreset: 'heart' } }, 96, 'b' );
		expect( a ).toContain( 'id="sa"' );
		expect( a ).toContain( 'href="#sa"' );
		expect( b ).toContain( 'id="sb"' );
		expect( a.match( /id="s[^"]*"/ )?.[ 0 ] ).not.toBe(
			b.match( /id="s[^"]*"/ )?.[ 0 ],
		);
	} );

	test( 'refuse to let a suffix break out of the attribute', () => {
		const svg = mioPortraitSvg( {}, 96, '" onload="alert(1)' );

		expect( svg ).toContain( 'id="sonloadalert1"' );
		expect( svg ).not.toContain( 'onload=' );
		expect( svg ).not.toContain( 'alert(' );
	} );

	test( 'size the box to the shape, not to a circle', () => {

		const box = ( preset: MioShapePreset ): number => {
			const svg = mioPortraitSvg( { physics: { shapePreset: preset } } );
			return Number( /viewBox="-([\d.]+)/.exec( svg )![ 1 ] );
		};
		expect( box( 'drop' ) ).toBeGreaterThan( box( 'star' ) );
		expect( box( 'star' ) ).toBeGreaterThan( box( 'blob' ) );

		expect( box( 'blob' ) ).toBeGreaterThan( box( 'circle' ) );
		expect( box( 'blob' ) ).toBeLessThan( box( 'circle' ) * 1.1 );
	} );

	test( 'fall back to the shipped look for anything not given', () => {
		const bare = mioPortraitSvg();
		expect( bare ).toContain(
			`fill="#${ MIO_DEFAULTS.appearance.bodyColor
				.toString( 16 )
				.padStart( 6, '0' ) }"`,
		);
	} );

	test( 'produce a data URI that decodes back to the same markup', () => {
		const config = { physics: { shapePreset: 'ghost' as const } };
		const uri = mioPortraitDataUri( config, 40 );
		expect( uri.startsWith( 'data:image/svg+xml;base64,' ) ).toBe( true );
		const decoded = Buffer.from(
			uri.slice( 'data:image/svg+xml;base64,'.length ),
			'base64',
		).toString( 'utf8' );
		expect( decoded ).toBe( mioPortraitSvg( config, 40 ) );
	} );
} );

describe( 'mulberry32', () => {
	test( 'gives the same look back for the same seed', () => {
		expect( randomMioLook( mulberry32( 7 ) ) ).toEqual(
			randomMioLook( mulberry32( 7 ) ),
		);
	} );

	test( 'gives different looks for different seeds', () => {
		const looks = [ 1, 2, 3, 4, 5, 6, 7, 8 ].map( ( s ) =>
			JSON.stringify( randomMioLook( mulberry32( s ) ) ),
		);
		expect( new Set( looks ).size ).toBe( looks.length );
	} );

	test( 'stays inside [0, 1)', () => {
		const rand = mulberry32( 0 );
		for ( let i = 0; i < 5000; i++ ) {
			const v = rand();
			expect( v ).toBeGreaterThanOrEqual( 0 );
			expect( v ).toBeLessThan( 1 );
		}
	} );
} );
