/**
 * Pure list of `<os-*>` tag names — no side effects, no class imports.
 *
 * Split out from `index.ts` so consumers that only need the tag list
 * (the COMPONENTS_REGISTERED action payload, the help-screen iterator,
 * tooling) do not drag every component module into their bundle.
 *
 * Keep in sync with the components actually defined under
 * `src/ui/components/`. The order matches the export order in
 * `index.ts`.
 */

export const OS_COMPONENT_TAGS = [
	'os-section',
	'os-button',
	'os-swatch',
	'os-swatch-grid',
	'os-segmented',
	'os-segment',
	'os-select',
	'os-option',
	'os-multiselect',
	'os-color-field',
	'os-range-field',
	'os-text-field',
	'os-number-field',
	'os-checkbox',
	'os-checkbox-label',
	'os-toast',
	'os-toast-container',
	'os-tabs',
	'os-tab',
	'os-tabpanel',
	'os-window-button',
	'os-menu',
	'os-menu-item',
	'os-context-menu',
	'os-context-menu-option',
	'os-confirm-dialog',
	'os-modal',
	'os-user-search',
	'os-role-picker',
	'os-flyout',
	'os-tab-chip',
	'os-stack',
	'os-cluster',
	'os-icon',
	'os-body',
	'os-panel',
	'os-row',
	'os-grid',
	'os-display',
	'os-empty-state',
	'os-key',
	'os-code',
	'os-badge',
	'os-ribbon',
	'os-tile',
	'os-log',
	'os-steps',
	'os-step',
	'os-table',
	'os-spinner',
	'os-relative-time',
	'os-avatar',
	'os-textarea',
	'os-chip',
	'os-tag-input',
	'os-form',
	'os-save-status',
	'os-category-picker',
	'os-crumb-chain',
	'os-card',
	'os-rating-summary',
	'os-notice',
	'os-progress-bar',
] as const;
