<?php
/**
 * phpMyAdmin configuration generated by wp-desktop-mode.
 *
 * Copied verbatim into `assets/vendor/phpmyadmin/config.inc.php` by
 * {@see desktop_mode_phpmyadmin_install_config()} so phpMyAdmin's bootstrap
 * picks it up automatically.
 *
 * Two paths covered, automatically:
 *
 *   - **Real MySQL/MariaDB** (`DB_USER` defined in wp-config.php) — use
 *     the WordPress site's DB credentials so phpMyAdmin auto-logs in
 *     as the same user WordPress uses.
 *   - **Studio / SQLite-backed installs** (`DB_USER` not defined) —
 *     fall back to the Studio convention (host=127.0.0.1, user=root,
 *     no password). Studio's Playground runtime intercepts mysqli
 *     calls at the PHP-extension level and routes them through a
 *     MySQL → SQLite translator, so phpMyAdmin doesn't need real
 *     MySQL credentials in this case — any 127.0.0.1/root config
 *     works.
 *
 * Always sets `AllowThirdPartyFraming = 'sameorigin'` because the
 * wp-desktop-mode shortcut embeds phpMyAdmin in an iframe; phpMyAdmin's
 * default `X-Frame-Options: DENY` blocks that. Same-origin gives us
 * the framing we need without opening up clickjacking from off-site.
 *
 * Only safe because the surrounding shortcut is gated to
 * `wp_get_environment_type() === 'local'` AND `manage_options` — see
 * `includes/window.php`.
 *
 * @package WPDesktopMode
 */

// Bootstrap WordPress so DB_* constants and helpers are available.
// Two key tricks:
//
//   1. Resolve the WP root via $_SERVER['DOCUMENT_ROOT'] FIRST. The
//      __DIR__ walk fallback breaks in Studio (and any setup that
//      symlinks the plugin into wp-content): __DIR__ resolves through
//      the symlink to the source checkout, where walking upward never
//      reaches wp-load.php.
//
//   2. Define SHORTINIT before requiring wp-load.php so WordPress
//      skips plugin/theme loading and most actions — we only need the
//      DB_* constants. Without SHORTINIT, including the iframe
//      request would re-run the full plugin stack (including this
//      module's `init` hook), which deadlocks.
$wpdc_pma_wp_root = '';
if ( ! empty( $_SERVER['DOCUMENT_ROOT'] ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotValidated, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
	$wpdc_pma_doc = rtrim( (string) $_SERVER['DOCUMENT_ROOT'], '/\\' ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.MissingUnslash
	if ( is_readable( $wpdc_pma_doc . '/wp-load.php' ) ) {
		$wpdc_pma_wp_root = $wpdc_pma_doc;
	}
	unset( $wpdc_pma_doc );
}
if ( '' === $wpdc_pma_wp_root ) {
	$wpdc_pma_walk = __DIR__;
	for ( $wpdc_pma_i = 0; $wpdc_pma_i < 12; $wpdc_pma_i++ ) {
		if ( is_readable( $wpdc_pma_walk . '/wp-load.php' ) ) {
			$wpdc_pma_wp_root = $wpdc_pma_walk;
			break;
		}
		$wpdc_pma_walk = dirname( $wpdc_pma_walk );
	}
	unset( $wpdc_pma_walk, $wpdc_pma_i );
}

if ( '' !== $wpdc_pma_wp_root && ! defined( 'ABSPATH' ) ) {
	if ( ! defined( 'SHORTINIT' ) ) {
		define( 'SHORTINIT', true );
	}
	// Silence WP's bootstrap entirely. We only need its constants;
	// any output (deprecation notices, chatter) corrupts phpMyAdmin's
	// response. Three layers:
	//
	//   1. `display_errors=0` and `error_reporting(0)` keep PHP from
	//      printing/triggering errors — but not enough on its own,
	//      since phpMyAdmin installed its own error handler BEFORE
	//      our config loaded, so PHP routes warnings there directly.
	//   2. Temporary error handler that returns true swallows
	//      everything, preventing PMA's handler from being called.
	//   3. ob_start/ob_end_clean discards anything printed despite
	//      the above (e.g. WP-WASM persists constants across
	//      requests, so redefining WP_DEBUG triggers a warning that
	//      we don't want surfacing).
	set_error_handler( function () { return true; }, E_ALL ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_set_error_handler
	$wpdc_pma_prev_display = @ini_set( 'display_errors', '0' ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
	$wpdc_pma_prev_report  = error_reporting( 0 );
	ob_start();
	require_once $wpdc_pma_wp_root . '/wp-load.php';
	ob_end_clean();
	error_reporting( $wpdc_pma_prev_report );
	@ini_set( 'display_errors', $wpdc_pma_prev_display ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
	restore_error_handler();
	unset( $wpdc_pma_prev_display, $wpdc_pma_prev_report );

	// Critical — WordPress hooks `wp_ob_end_flush_all` onto `shutdown`,
	// which forcibly flushes every open output buffer (including
	// phpMyAdmin's main response buffer) before phpMyAdmin can send its
	// headers. The result is the response body leaking to the client
	// halfway through render, then phpMyAdmin's later `header()` calls
	// fail with "headers already sent" and its error handler clears the
	// response — leaving the iframe blank. phpMyAdmin owns its own
	// flushing; remove WP's competing one.
	if ( function_exists( 'remove_action' ) ) {
		remove_action( 'shutdown', 'wp_ob_end_flush_all', 1 );
	}
}
unset( $wpdc_pma_wp_root );

// Hard gate on the vendor entrypoint.
//
// `assets/vendor/phpmyadmin/index.php` is directly reachable as a PHP
// file under `wp-content/plugins/`. The capability + environment gate
// in `window.php` only controls whether the desktop *icon* is shown —
// it doesn't stop the web server from executing this file. Without
// the gate below, an internet-exposed install that ships the plugin
// would expose the WordPress DB credentials baked into the
// `auth_type = config` block further down to any unauthenticated
// visitor that finds the URL.
//
// We enforce ONLY the environment check here, not the capability
// check. Two reasons:
//
//   1. The environment check is the load-bearing one — it's what
//      closes the production-fail-open hole. The capability check is
//      already enforced reliably on the icon side
//      (`desktop_mode_phpmyadmin_user_can_use()` in `window.php`), so a low-
//      privilege user can't discover the URL through the UI in the
//      first place.
//   2. SHORTINIT above skipped pluggable.php / user.php / capabilities
//      / the role classes — `current_user_can()` doesn't exist yet
//      and synthesising it (manual `require_once` of those files +
//      a fresh `wp_validate_auth_cookie()` round-trip) is fragile in
//      this no-init context. Several setups (wp-env, WordPress
//      Develop, wasm) have surfaced cases where the cookie validation
//      silently returns no-user even for an authenticated admin,
//      locking out legitimate local devs while adding little real
//      defence on top of the icon-side gate.
//
// On failure, return 404 (not 403) so the existence of the entrypoint
// isn't disclosed to probes on misconfigured production installs.
if ( ! function_exists( 'wp_get_environment_type' )
	|| 'local' !== wp_get_environment_type()
) {
	if ( ! headers_sent() ) {
		header( 'HTTP/1.0 404 Not Found' );
	}
	exit;
}

// Override session save path — wasm/Playground default points at a
// non-existent dir (`/home/web_user`), breaking phpMyAdmin's first
// session_start. sys_get_temp_dir() resolves to a writable location
// in every PHP environment we've tested.
$wpdc_pma_session_dir = rtrim( sys_get_temp_dir(), '/\\' ) . '/wpdc-phpmyadmin-sessions';
if ( ! is_dir( $wpdc_pma_session_dir ) ) {
	@mkdir( $wpdc_pma_session_dir, 0700, true ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
}
if ( is_dir( $wpdc_pma_session_dir ) && is_writable( $wpdc_pma_session_dir ) ) {
	@ini_set( 'session.save_path', $wpdc_pma_session_dir ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
}
unset( $wpdc_pma_session_dir );

// phpMyAdmin's own verbose error reporting (matches Studio's bundle).
$cfg['environment'] = 'development';

// Allow same-origin framing so the wp-desktop-mode iframe can embed
// phpMyAdmin. By default phpMyAdmin sends `X-Frame-Options: DENY`,
// which the browser enforces strictly — there's no JS workaround.
$cfg['AllowThirdPartyFraming'] = 'sameorigin';

// 32-byte secret for short-lived cookie crypto. Derived from AUTH_KEY
// so it stays stable across requests without a separate constant.
$cfg['blowfish_secret'] = defined( 'AUTH_KEY' )
	? substr( hash( 'sha256', AUTH_KEY ), 0, 32 )
	: str_repeat( '0', 32 );

$i = 1;
$cfg['Servers'][ $i ]['auth_type'] = 'config';
$cfg['Servers'][ $i ]['compress']  = false;

if ( defined( 'DB_USER' ) ) {
	// Real MySQL/MariaDB site — use WordPress's credentials so
	// phpMyAdmin connects to exactly the same DB WP does.
	$cfg['Servers'][ $i ]['host']            = defined( 'DB_HOST' ) ? DB_HOST : 'localhost';
	$cfg['Servers'][ $i ]['user']            = DB_USER;
	$cfg['Servers'][ $i ]['password']        = defined( 'DB_PASSWORD' ) ? DB_PASSWORD : '';
	$cfg['Servers'][ $i ]['only_db']         = defined( 'DB_NAME' ) ? DB_NAME : '';
	$cfg['Servers'][ $i ]['AllowNoPassword'] = false;
} else {
	// No DB_USER — likely a Studio site (or other Playground-backed
	// install) where wp-config.php skips DB constants because the
	// runtime injects them via SQLite. Match Studio's bundled
	// phpMyAdmin config so the SQLite translator picks the connection
	// up correctly.
	$cfg['Servers'][ $i ]['host']            = '127.0.0.1';
	$cfg['Servers'][ $i ]['user']            = 'root';
	$cfg['Servers'][ $i ]['password']        = '';
	$cfg['Servers'][ $i ]['AllowNoPassword'] = true;
}

$cfg['ServerDefault']                 = 1;
$cfg['CheckConfigurationPermissions'] = false;
$cfg['ShowServerInfo']                = false;
$cfg['NavigationDisplayLogo']         = false;
$cfg['DefaultLang']                   = 'en';

// phpMyAdmin's navigation-tree prefix grouping uses MySQL's
// `SUBSTRING_INDEX` to fold databases like `wp_blog1` / `wp_blog2`
// under a `wp_` parent. SQLite has no such function and Studio's
// MySQL→SQLite translator doesn't emulate it, so the nav-tree query
// silently throws and the tree renders empty. Disabling grouping
// makes phpMyAdmin fall back to a simpler listing query.
$cfg['NavigationTreeEnableGrouping'] = false;
